apiVersion: v1
kind: Service
metadata:
  name: sms
spec:
  ports:
  - port: 3000
    targetPort: 8080
  selector:
    app: sms
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms
spec:
  selector:
    matchLabels:
      app: sms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sms
    spec:
      containers:
      - image: ghcr.io/mercatia/stockmarketsimulator:sha-92c2c21
        name: sms
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: stock_trading_simulator
        ports:
        - containerPort: 8080
          name: sms


